In [4]:
import pandas as pd
import time
import numpy as np
from preprocess import Preprocessor
# Scikit Learn Libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import VotingClassifier
from sklearn import metrics
# XGBoost Library
from xgboost import XGBClassifier

def random_forest(X_train, y_train, X_test, y_test):

    clf = RandomForestClassifier(n_estimators=200, max_depth=12, random_state=0, min_samples_split=3, n_jobs=-1)
    clf = clf.fit(X_train, y_train)
    expected = y_test
    predicted = clf.predict(X_test)

    print("Classification report for classifier %s:\n%s\n"
          % (clf, metrics.classification_report(expected, predicted)))
    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
    print 'Score: '
    print clf.score(X_test,y_test)
    print ' '
    
def neural_network(X_train, y_train, X_test, y_test):
    
    clf = MLPClassifier(hidden_layer_sizes=(64,32))
    clf = clf.fit(X_train, y_train)
    expected = y_test
    predicted = clf.predict(X_test)

    print("Classification report for classifier %s:\n%s\n"
          % (clf, metrics.classification_report(expected, predicted)))
    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
    print 'Score: '
    print clf.score(X_test,y_test)
    print ' '
    
def XGboost(X_train, y_train, X_test, y_test):

    clf = XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.05, min_child_weight=2, 
                        n_jobs=-1, max_delta_step=1, objective='binary:logistic', gamma=3 ,subsample=1)
    clf = clf.fit(X_train, y_train)
    expected = y_test
    predicted = clf.predict(X_test)

    print("Classification report for classifier %s:\n%s\n"
          % (clf, metrics.classification_report(expected, predicted)))
    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
    print 'Score: '
    print clf.score(X_test,y_test)
    print ' '
    
def voting(X_train, y_train, X_test, y_test):
    
    clf1 = RandomForestClassifier(n_estimators=200, max_depth=12, random_state=0, min_samples_split=3, n_jobs=-1)
    clf2 = MLPClassifier(hidden_layer_sizes=(64,32))
    clf3 = XGBClassifier(n_estimators=200, max_depth=6, learning_rate=0.05, min_child_weight=2, 
                        n_jobs=-1, max_delta_step=1, objective='binary:logistic', gamma=3 ,subsample=1)
    
    clf = VotingClassifier(estimators=[('rf', clf1), ('nn', clf2), ('xgb', clf3)], voting='hard')
    clf = clf.fit(X_train, y_train)
    expected = y_test
    predicted = clf.predict(X_test)

    print("Classification report for classifier %s:\n%s\n"
          % (clf, metrics.classification_report(expected, predicted)))
    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
    print 'Score: '
    print clf.score(X_test,y_test)
    
def main():
    
    # Build preprocessor
    p_train = Preprocessor('train')
    p_test = Preprocessor('test')
    
    # Get value
    X_train, y_train = p_train.get_values_all()
    X_test, y_test = p_test.get_values_all()
    
    # Random forest
    random_forest(X_train, y_train, X_test, y_test)
    
    # Neural network
    neural_network(X_train, y_train, X_test, y_test)
    
    # XGboost
    XGboost(X_train, y_train, X_test, y_test)
    
    # Voting
    voting(X_train, y_train, X_test, y_test)

if __name__== "__main__":
  main()

load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 4677908)
('number of enrollment_ids:', 72395)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 72395)
('number of uers: ', 53870)
load truth info over!
('number of labels:', 72395)
load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 1548480)
('number of enrollment_ids:', 24013)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 24013)
('number of uers: ', 21266)
load truth info over!
('number of labels:', 24013)
event_count features extracted! 1.151504 seconds taken
('Shape of the event_count dataframe: ', (72395, 8))
weekly_session_count features extracted! 57.241510 seconds taken
('Shape of th

In [2]:
import pandas as pd
import time
import numpy as np
from preprocess import Preprocessor
# Scikit Learn Libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
# XGBoost Library
from xgboost import XGBClassifier

In [3]:
# Build preprocessor
p_train = Preprocessor('train')
p_test = Preprocessor('test')

# Get value
X_train, y_train = p_train.get_values_all()
X_test, y_test = p_test.get_values_all()

load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 4677908)
('number of enrollment_ids:', 72395)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 72395)
('number of uers: ', 53870)
load truth info over!
('number of labels:', 72395)
load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 1548480)
('number of enrollment_ids:', 24013)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 24013)
('number of uers: ', 21266)
load truth info over!
('number of labels:', 24013)
event_count features extracted! 1.134946 seconds taken
('Shape of the event_count dataframe: ', (72395, 8))
weekly_session_count features extracted! 58.485489 seconds taken
('Shape of th

In [8]:
t0 = time.time()
clf = RandomForestClassifier(n_estimators=10,random_state=0)
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
t1 = time.time()
print cross_val_score(clf, X_train, y_train, cv=5)
print t1 - t0

Classification report for classifier RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False):
              precision    recall  f1-score   support

           0       0.67      0.60      0.63      4902
           1       0.90      0.93      0.91     19111

   micro avg       0.86      0.86      0.86     24013
   macro avg       0.79      0.76      0.77     24013
weighted avg       0.85      0.86      0.86     24013


Confusion matrix:
[[ 2926  1976]
 [ 1411 17700]]
Score: 
0.8589514013242827
[0.85600829 0.86007321 0.86214518 0.85731059 0.86089239]
1.02198886871


In [4]:
clf = RandomForestClassifier(n_estimators=100,random_state=0)
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print cross_val_score(clf, X_train, y_train, cv=5)

Classification report for classifier RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False):
              precision    recall  f1-score   support

           0       0.74      0.57      0.65      4902
           1       0.90      0.95      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.82      0.76      0.78     24013
weighted avg       0.86      0.87      0.87     24013


Confusion matrix:
[[ 2800  2102]
 [  979 18132]]
Score: 
0.8716944988131429
[0.87023481 0.87278127 0.8747151  0.87064024 0.87056223]


In [9]:
t0 = time.time()
clf = RandomForestClassifier(n_estimators=500,random_state=0)
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
t1 = time.time()
print t1 - t0
#print cross_val_score(clf, X_train, y_train, cv=5)

Classification report for classifier RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False):
              precision    recall  f1-score   support

           0       0.75      0.57      0.65      4902
           1       0.90      0.95      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.82      0.76      0.78     24013
weighted avg       0.87      0.87      0.87     24013


Confusion matrix:
[[ 2786  2116]
 [  932 18179]]
Score: 
0.8730687544246867
42.7044689655


In [13]:
t0 = time.time()
clf = svm.SVC(gamma='scale') 
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
t1 = time.time()
print t1 - t0
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
              precision    recall  f1-score   support

           0       0.75      0.53      0.62      4902
           1       0.89      0.95      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.82      0.74      0.77     24013
weighted avg       0.86      0.87      0.86     24013


Confusion matrix:
[[ 2619  2283]
 [  876 18235]]
Score: 
0.8684462582767668
Cross validation score: 
552.128526926


In [10]:
t0 = time.time()
clf = MLPClassifier(hidden_layer_sizes=(50,50))
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
t1 = time.time()
print t1 - t0
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False):
              precision    recall  f1-score   support

           0       0.72      0.57      0.64      4902
           1       0.90      0.94      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.81      0.76      0.78     24013
weighted avg       0.86      0.87      0.86     24013


Confusion matrix:
[[ 2812  2090]
 [ 1079 18032]]
Score: 
0.8680298171823596
Cross validation score: 
76.4239008427


In [5]:
clf = MLPClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False):
              precision    recall  f1-score   support

           0       0.82      0.45      0.58      4902
           1       0.87      0.97      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.85      0.71      0.75     24013
weighted avg       0.86      0.87      0.85     24013


Confusion matrix:
[[ 2198  2704]
 [  480 18631]]
Score: 
0.8674051555407487
Cross validation score: 


In [6]:
clf = MLPClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False):
              precision    recall  f1-score   support

           0       0.77      0.55      0.64      4902
           1       0.89      0.96      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.83      0.75      0.78     24013
weighted avg       0.87      0.87      0.87     24013


Confusion matrix:
[[ 2701  2201]
 [  808 18303]]
Score: 
0.8746928746928747
Cross validation score: 


In [11]:
# Logistic regression
t0 = time.time()
clf = LogisticRegression()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
t1 = time.time()
print t1 - t0
#print cross_val_score(clf, X_train, y_train, cv=3)

/anaconda2/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Classification report for classifier LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False):
              precision    recall  f1-score   support

           0       0.80      0.50      0.62      4902
           1       0.88      0.97      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.84      0.74      0.77     24013
weighted avg       0.87      0.87      0.86     24013


Confusion matrix:
[[ 2465  2437]
 [  604 18507]]
Score: 
0.8733602631907716
Cross validation score: 
0.772509098053


In [12]:
# Gradient Boosting
t0 = time.time()
clf = GradientBoostingClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
t1 = time.time()
print t1 - t0
#print cross_val_score(clf, X_train, y_train, cv=5)

Classification report for classifier GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False):
              precision    recall  f1-score   support

           0       0.76      0.57      0.65      4902
           1       0.90      0.95      0.92     19111

   micro avg       0.88      0.88      0.88     24013
   macro avg       0.83      0.76      0.79     24013
weighted avg       0.87      0.88      0.87     24013


Confusion matrix:
[[ 2811  2091]
 [  874 18237]]
Score: 
0.8765252155082663
Cross validat

In [16]:
# Ada Boosting

clf = AdaBoostClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
print cross_val_score(clf, X_train, y_train, cv=5)

Classification report for classifier AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None):
              precision    recall  f1-score   support

           0       0.77      0.55      0.64      4902
           1       0.89      0.96      0.92     19111

   micro avg       0.88      0.88      0.88     24013
   macro avg       0.83      0.75      0.78     24013
weighted avg       0.87      0.88      0.87     24013


Confusion matrix:
[[ 2686  2216]
 [  784 18327]]
Score: 
0.8750676716778412
Cross validation score: 
[0.87216851 0.87457697 0.8751295  0.87540576 0.8743611 ]
