In [6]:
import pandas as pd
import time
import numpy as np
from preprocess import Preprocessor
# Scikit Learn Libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression

def random_forest(X_train, y_train, X_test, y_test, N_estimators=500):

    clf = RandomForestClassifier(n_estimators=500)
    clf = clf.fit(X_train, y_train)
    expected = y_test
    predicted = clf.predict(X_test)

    print("Classification report for classifier %s:\n%s\n"
          % (clf, metrics.classification_report(expected, predicted)))
    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
    print 'Score: '
    print clf.score(X_test,y_test)

def SVM(X_train, y_train, X_test, y_test, Gamma='scale'):

    clf = svm.SVC(gamma='scale') 
    clf = clf.fit(X_train, y_train)
    expected = y_test
    predicted = clf.predict(X_test)

    print("Classification report for classifier %s:\n%s\n"
          % (clf, metrics.classification_report(expected, predicted)))
    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
    print 'Score: '
    print clf.score(X_test,y_test)
    print 'Cross validation score: '
    print cross_val_score(clf, X_train, y_train, cv=3)
    
def MLPClassifier(X_train, y_train, X_test, y_test):
    
    clf = MLPClassifier()
    clf = clf.fit(X_train, y_train)
    expected = y_test
    predicted = clf.predict(X_test)

    print("Classification report for classifier %s:\n%s\n"
          % (clf, metrics.classification_report(expected, predicted)))
    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
    print 'Score: '
    print clf.score(X_test,y_test)
    print 'Cross validation score: '
    print cross_val_score(clf, X_train, y_train, cv=3)
    
    
def main():
    
    # Build preprocessor
    p_train = Preprocessor('train')
    p_test = Preprocessor('test')
    
    # Get value
    X_train, y_train = p_train.get_values_all()
    X_test, y_test = p_test.get_values_all()
    
    # Random forest: N_estimators
    random_forest(X_train, y_train, X_test, y_test, N_estimators=500)
    
    # SVM: gamma
    SVM(X_train, y_train, X_test, y_test, Gamma='scale')
    
    # Neural network
    neural_network(X_train, y_train, X_test, y_test)
    

if __name__== "__main__":
  main()

load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 4677908)
('number of enrollment_ids:', 72395)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 72395)
('number of uers: ', 53870)
load truth info over!
('number of labels:', 72395)
load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 1548480)
('number of enrollment_ids:', 24013)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 24013)
('number of uers: ', 21266)
load truth info over!
('number of labels:', 24013)
event_count features extracted! 1.532409 seconds taken
('Shape of the event_count dataframe: ', (72395, 8))
weekly_event_count features extracted! 3.781156 seconds taken
('Shape of the w

In [18]:
import pandas as pd
import time
import numpy as np
from preprocess import Preprocessor
# Libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn import svm
from sklearn.model_selection import cross_val_score
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier

ImportError: No module named xgboost

In [2]:
# Build preprocessor
p_train = Preprocessor('train')
p_test = Preprocessor('test')

# Get value
X_train, y_train = p_train.get_values_all()
X_test, y_test = p_test.get_values_all()

load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 4677908)
('number of enrollment_ids:', 72395)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 72395)
('number of uers: ', 53870)
load truth info over!
('number of labels:', 72395)
load course date info over!
('number of courses:', 39)
load course object info over!
('number of courses:', 39)
('number of moduels:', 26750)
load course object info over!
('size of log data:', 1548480)
('number of enrollment_ids:', 24013)
load enrollment info over!
('number of courses:', 39)
('number of enrollments:', 24013)
('number of uers: ', 21266)
load truth info over!
('number of labels:', 24013)
event_count features extracted! 1.141020 seconds taken
('Shape of the event_count dataframe: ', (72395, 8))
weekly_session_count features extracted! 63.178121 seconds taken
('Shape of th

In [11]:
clf = RandomForestClassifier(n_estimators=500)
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print cross_val_score(clf, X_train, y_train, cv=5)

Classification report for classifier RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False):
              precision    recall  f1-score   support

           0       0.75      0.57      0.65      4902
           1       0.90      0.95      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.82      0.76      0.78     24013
weighted avg       0.87      0.87      0.87     24013


Confusion matrix:
[[ 2785  2117]
 [  924 18187]]
Score: 
0.8733602631907716
[0.87051105 0.87436978 0.87354099 0.87257407 0.87263434]


In [ ]:
clf = svm.SVC(gamma='scale') 
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False):
              precision    recall  f1-score   support

           0       0.71      0.58      0.64      4902
           1       0.90      0.94      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.81      0.76      0.78     24013
weighted avg       0.86      0.87      0.86     24013


Confusion matrix:
[[ 2824  2078]
 [ 1127 17984]]
Score: 
0.8665306292424937
Cross validation score: 


In [4]:
clf = MLPClassifier(hidden_layer_sizes=(50,50))
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(50, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False):
              precision    recall  f1-score   support

           0       0.76      0.52      0.62      4902
           1       0.89      0.96      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.82      0.74      0.77     24013
weighted avg       0.86      0.87      0.86     24013


Confusion matrix:
[[ 2562  2340]
 [  815 18296]]
Score: 
0.8686128347145297
Cross validation score: 


In [5]:
clf = MLPClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False):
              precision    recall  f1-score   support

           0       0.82      0.45      0.58      4902
           1       0.87      0.97      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.85      0.71      0.75     24013
weighted avg       0.86      0.87      0.85     24013


Confusion matrix:
[[ 2198  2704]
 [  480 18631]]
Score: 
0.8674051555407487
Cross validation score: 


In [6]:
clf = MLPClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False):
              precision    recall  f1-score   support

           0       0.77      0.55      0.64      4902
           1       0.89      0.96      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.83      0.75      0.78     24013
weighted avg       0.87      0.87      0.87     24013


Confusion matrix:
[[ 2701  2201]
 [  808 18303]]
Score: 
0.8746928746928747
Cross validation score: 


In [10]:
# Logistic regression

clf = LogisticRegression()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
#print cross_val_score(clf, X_train, y_train, cv=3)

Classification report for classifier LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False):
              precision    recall  f1-score   support

           0       0.80      0.50      0.62      4902
           1       0.88      0.97      0.92     19111

   micro avg       0.87      0.87      0.87     24013
   macro avg       0.84      0.74      0.77     24013
weighted avg       0.87      0.87      0.86     24013


Confusion matrix:
[[ 2465  2437]
 [  604 18507]]
Score: 
0.8733602631907716
Cross validation score: 


In [14]:
# Gradient Boosting

clf = GradientBoostingClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
print cross_val_score(clf, X_train, y_train, cv=5)

Classification report for classifier GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False):
              precision    recall  f1-score   support

           0       0.76      0.57      0.65      4902
           1       0.90      0.95      0.92     19111

   micro avg       0.88      0.88      0.88     24013
   macro avg       0.83      0.76      0.79     24013
weighted avg       0.87      0.88      0.87     24013


Confusion matrix:
[[ 2811  2091]
 [  873 18238]]
Score: 
0.8765668596177071
Cross validat

In [16]:
# Ada Boosting

clf = AdaBoostClassifier()
clf = clf.fit(X_train, y_train)
expected = y_test
predicted = clf.predict(X_test)

print("Classification report for classifier %s:\n%s\n"
      % (clf, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))
print 'Score: '
print clf.score(X_test,y_test)
print 'Cross validation score: '
print cross_val_score(clf, X_train, y_train, cv=5)

Classification report for classifier AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None):
              precision    recall  f1-score   support

           0       0.77      0.55      0.64      4902
           1       0.89      0.96      0.92     19111

   micro avg       0.88      0.88      0.88     24013
   macro avg       0.83      0.75      0.78     24013
weighted avg       0.87      0.88      0.87     24013


Confusion matrix:
[[ 2686  2216]
 [  784 18327]]
Score: 
0.8750676716778412
Cross validation score: 
[0.87216851 0.87457697 0.8751295  0.87540576 0.8743611 ]
